var TABLE_NAME = 'TCDA_USR_RSM';
var RESUME_DATA_TABLE_NAME = 'TCDA_RSM_DATA';
var SHARED_INFO_TABLE_NAME = 'TCDA_RSM_SHR_INFO';

/**
 * Prepared query for ResumeDAO. <br />
 * 
 * @since 180326
 * @author TACKSU
 */
module.exports = {
    put: 'INSERT INTO ' + TABLE_NAME + ' SET ?',
    get: 'SELECT * FROM ' + TABLE_NAME + ' WHERE ',
    set: 'UPDATE ' + TABLE_NAME + ' SET ? WHERE ?',
    delResume: "UPDATE " + TABLE_NAME + " SET DEL_YN = 'Y' WHERE ?",

    putResumeRecords: 'INSERT INTO ' + RESUME_DATA_TABLE_NAME + ' SET ?',
    getResumeRecords: 'SELECT * FROM ' + RESUME_DATA_TABLE_NAME + ' WHERE ? ',
    setResumeRecords: 'UPDATE ' + RESUME_DATA_TABLE_NAME + ' SET ? WHERE ?',
    delResumeRecords: "UPDATE " + RESUME_DATA_TABLE_NAME + " SET DEL_YN = 'Y' WHERE ? and ?",


    putUrl: 'INSERT INTO ' + SHARED_INFO_TABLE_NAME + ' SET ?',
    
    isShareURL: 'SELECT * FROM ' + SHARED_INFO_TABLE_NAME + " WHERE DEL_YN = 'N' and ?",
    
    getUrl: "SELECT TUR.UPDT_STS, TUR.TITLE, TUR.INTRO, TUR.SHRD_YN, TSD.TRX_ID, TSD.ENC_RSM_DATA, TRSI.URL, TRSI.RSM_ID, TRSI.PUB_YN, TRSI.PASSCODE, TRSI.EXPIRED_DT FROM " + SHARED_INFO_TABLE_NAME + " AS TRSI INNER JOIN TCDA_USR_RSM AS TUR ON (TUR.RSM_ID = TRSI.RSM_ID AND TUR.DEL_YN = 'N') INNER JOIN TCDA_RSM_DATA AS TSD ON (TSD.RSM_ID = TRSI.RSM_ID AND TSD.DEL_YN = 'N') WHERE TRSI.DEL_YN = 'N' AND ?",
    
    getUrlPrvt: "SELECT TUR.UPDT_STS, TUR.TITLE, TUR.INTRO, TUR.SHRD_YN, TCP.ENC_PRVT_DATA, TRSI.URL, TRP.ORDER, TRSI.RSM_ID, TRSI.PUB_YN, TRSI.PASSCODE, TRSI.EXPIRED_DT FROM TCDA_RSM_SHR_INFO AS TRSI INNER JOIN TCDA_USR_RSM AS TUR ON (TUR.RSM_ID = TRSI.RSM_ID AND TUR.DEL_YN = 'N') INNER JOIN TCDA_RSM_PRVT AS TRP ON (TRP.RSM_ID = TRSI.RSM_ID AND TRP.DEL_YN = 'N') INNER JOIN TCDA_CERT_PRVT AS TCP ON (TCP.CERT_PRVT_ID = TRP.CERT_PRVT_ID AND TCP.DEL_YN = 'N')    WHERE TRSI.DEL_YN = 'N' AND ?",
    setUrl: 'UPDATE ' + SHARED_INFO_TABLE_NAME + ' SET ? WHERE ?',
    
    delUrl: 'UPDATE ' + SHARED_INFO_TABLE_NAME + " SET DEL_YN = 'Y' WHERE ? and ?"
}